### ISSUE TITLE
MVP List Review

### ISSUE THREAD

**Issue by ssoonmi** [MLT-NYC/mxpx#1]
- [x] galleries should not be part of your core features. You can make it a bonus feature for later!

### Profile Page
- [x] should show all the photos for a user
- [x] should be able to see all the followers for a user and who is following that user

Great job! If you have any comments/concerns about any of this, comment below or Slack me!

**Comment by MLT-NYC** [comment]
Thank you for pointing this out! I have removed galleries from the core features in the home feed, and replaced them with users being able to view public pictures and make comments. I also updated the profile page to show your suggestions.
